namespace WAK.AutoGenerated
{
    public enum AudioClipType
    {
        BGM_grieg_peer_gynt_morning_mood,
        BGM_gymnopedie_no_1,
        SFX_drop_1,
        SFX_drop_2,
        SFX_ui_click,
        SFX_ui_hover,
    }
}
